name: 'PlayCanvas'
description: 'Download a PlayCanvas project'
inputs:
  project-id:
    description: 'The PlayCanvas project ID to download'
    required: true
  name:
    description: 'Reference name for the project'
    required: false
  scenes:
    description: 'A csv list of scene ids to be included in the app. If not specified, all scenes will be downloaded. When you specify scenes then the first scene in the list will be used as the initial scene of the application.'
    required: false
  version:
    description: 'The version of the app. Can be a string up to 20 characters. If none supplied it will use the latest checkpooint'
    required: false
  branch: 
    description: 'The id of the branch. If no id is specified the master branch will be used.'
    required: false
    default: 'master'
  concatenate-scripts:
    description: 'Set it to true if you want scripts to be concatenated'
    required: false
    default: true
  minify-scripts:
    description: 'Set it to true if you want scripts to be minified'
    required: false
    default: true
  mangle-scripts:
    description: 'Mangles scripts properties when true and if minify scripts is true'
    required: false
    default: false
  optimize-scene-format:
    description: 'Set it to true if you want scenes to be in an optimized format'
    required: false
    default: true
  engine-version:
    description: 'Set it to a Engine version string if a specific version is needed for the app.'
    required: false
  playcanvas-access-token :
    description: 'The Access Token for your PlayCanvas account'
    required : true
  excludeIndex :
    description: 'When true, the default PlayCanvas index.html file is not downloaded'
    default : false
  dir :
    description: 'The relative directory to download the project into'
    default : './'
outputs:
  artifact-name: # id of output
    description: 'The name of the artefact uploaded'
runs:
  using: 'node16'
  main: 'dist/index.js'
